apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Add ssh-pub-key to AWS iam user and paste SSH key ID you get here
    repoURL: ssh://<YOURSSHKEY>@git-codecommit.<region>.amazonaws.com/v1/repos/argocd-test
    targetRevision: master
    path: apps/nginx-test
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-test
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
