apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nginx-secret
  namespace: nginx-test
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: sample-secretstore
  target:
    # Secret name like in metadata
    name: nginx-secret
    creationPolicy: Owner
  data:
    # Filename that will be created in the pod containing the secret
  - secretKey: secret.txt
    remoteRef:
      # Name of the secret in AWS SecretsManager
      key: /argo/test1
